# Generated by Django 5.0.1 on 2024-01-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='pdf',
            field=models.FileField(default='default.pdf', upload_to='pdfs/'),
        ),
    ]
