# Generated by Django 5.0.1 on 2024-02-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_libro_descripcion_descargalibro_delete_producto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DescargaLibro',
        ),
    ]
